### PR TITLE
task: update dependencies

### PR DESCRIPTION
**Pull request by chrisman**
fixes a High security vulnerability with tar@3

the dep chain is node-sass > node-gyp > tar

Fixed by editing the lockfile as suggested here:
https://github.com/sass/node-sass/issues/2625#issuecomment-482224111

## Description
After merging this in you must do the following:
1. `rm -rf node_modules`
2. `npm i` (if this fails, try `npm cache clear --force`, and try again)

## Types of changes

- [x] chore or task: a change that doesn't effect executable code
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by chrisman** [comment]
@prowe214 I haven't been keeping up that closely. are we ignoring these lint errors for now? If not, I can fix them here as part of this PR.

**Comment by prowe214** [comment]
@chrisman Go ahead and kill them.  

Those console.logs are there because I thought I needed to merge them into `develop` in order to get them to deploy to heroku, but I found out I can deploy my feature branch directly.  So I've been deploying the branch I've been working on directly to heroku instead without needing to merge.  So develop should be clean.

**Comment by prowe214** [comment]
Thanks for taking this! 🛠

**Comment by chrisman** [comment]
I take that to mean I can remove them?

**Comment by prowe214** [comment]
👍 Yah, you can remove these console.logs so the linting is clean

**Review by prowe214 — APPROVED** [review]
🛠💪🎉

**Comment by chrisman** [comment]
will you double check this and try actually running it? `npm start` gives me errors about missing dotenv and mapbox-gl. which I don't understand at first glance, because they're definitely installed...

**Comment by prowe214** [comment]
@chrisman Yeah I'm getting those errors too using docker.  Doesn't arise when simply running `npm run serve` though.  I'll dig in...

**Comment by chrisman** [comment]
just gonna nuke this and start it over rather than deal with the staleness

**Pull request closed without merging**
