### PR TITLE
Docker update

### PR DESCRIPTION
**Pull request by JacobN256**
Added docker-compose to the Stumbl project in preparation for the MonoRepo approach.

## Description
- Added `Dockerfile.web`, `docker-compose.yml`
- Added `docker` cmd to `package.json` file for starting the dev environment using docker
- Fixed issue with import on `Counter.vue`

## Related Issue
https://github.com/Skookum/stumbl-2019/issues/17

## Types of changes
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [N/A] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by JacobN256** [comment]
I need to update the README.md file, but I wanted to make sure everyone is happy with the changes I made beforehand.  I'll update it once we agree 👍

**Comment by chrisman** [comment]
```
Failed to compile.

./src/main.ts
Module not found: Error: [CaseSensitivePathsPlugin] `/work/src/app.vue` does not match the corresponding path on disk `App.vue`.
```

screen shot 2019-02-08 at 11 50 45 am

Fixed in commit: https://github.com/Skookum/stumbl-2019/pull/20/commits/bed2827ce067a7826dca45e0d06f57cf789891a3

**Review by chrisman — APPROVED** [review]
👍
approved pending updating the docs

**Review by andylushman — APPROVED** [review]
Nice job!

**Pull request merged**
